### ISSUE TITLE
Estender o atual OWRL

### ISSUE THREAD

**Issue by andre-paraense** [CST-Group/cst#19]
- Hoje, apesar de na estrutura conceitual do OWRL termos os conceitos de Episode e Scene, esses conceitos não estão materializados de fato no CST. Precisaríamos de fato criar classes para esses conceitos de tal forma a permitir seu uso no System 2.
- Particularmente, o suporte que damos ao OWRL no CST se limita aos AbstractObjects e seus derivados. Me preocupa o fato de que não damos suporte a coisas que os WMEs no SOAR possuem, por exemplo a possibilidade de relações entre objetos, que hoje não são suportadas adequadamente no OWRL.
- O ideal seria fazermos um brainstorm para repensar o OWRL como instrumento de representação do conhecimento e compará-lo aos WMEs no SOAR ou os chunks no ACT-R ... e talvez até mesmo às estruturas de dados do OpenCog (que eu não conheço direito). Talvez incluir as representações vetoriais que o Wander anda estudando como uma modalidade de representação no OWRL.

**Comment by rgudwin** [comment]
A estrutura base do OWRL está em processo de ser deprecada, em favor da classe Idea. Ao invés de termos uma classe AbstractObject, uma classe Property, uma classe QualityDimension (e talvez Episode e Scene), a ideia é utilizar somente a classe Idea, e atrelar a ela uma outra Idea, com nome "type" e um valor com o tipo de Idea ("AbstractObject", "Property", "QualityDimension", "Episode", "Scene" e quantas mais forem necessárias. Com isso, utiliza-se uma única classe Java para representar qualquer tipo de conhecimento, independente do tipo que ele tenha. Isso já é possível com a classe Idea. O que precisa ainda ser feito é criar-se um mecanismo de geração de Templates de Ideas, para criar mais facilmente um AbstractObject, uma Property ou outro tipo de Idea.
