### ISSUE TITLE
No Exception if insert Codelet with non-existing groupName

### ISSUE THREAD

**Issue by wandgibaut** [CST-Group/cst#25]
On the method ** public void registerCodelet(Codelet co, String groupName)**, the **Mind** class gives no Exception or warning message if someone tries to insert a Codelet with a non-existing group. The codelet is inserted, but the group adding is ignored. Consider implementing the creation of a group with the given groupName.

**Comment by rgudwin** [comment]
Maybe it will be better to warn the user with a message that the group does not exist. It might be a typo in the group name, and creating a new group with the given name might make things worse. Warning the user will allow a correction in the case of a typo, and will sign that a group should be created before the registration.

**Comment by rgudwin** [comment]
This was corrected in version 1.4.2
