### ISSUE TITLE
Max Policy generating strange colateral efects.

### ISSUE THREAD

**Issue by brgsil** [CST-Group/cst#54]
Sequential getI() calls to a MemoryContainer returns different Objects even if the evaluations have not changed.
Multiples memories have the same value, therefore a random one is selected to be returned when getI() is called, but the random selection occurs every call, even if the evaluation values stayed the same between calls. 

https://github.com/CST-Group/cst/blob/4b9b69afab3812b5513b4fd1a405954cd7f828ec/src/main/java/br/unicamp/cst/core/entities/MemoryContainer.java#L127

**Comment by rgudwin** [comment]
This was corrected in CST v. 1.4.2. New tests were included to verify that in many situations. In the case of MIN and MAX policies, now in the case of having more than one possible return, it will choose it randomly, but the chosen one will remain until a new setI is generated. For the case of RANDOM_FLAT and RANDOM_PROPORTIONAL policies, two new policies were included: RANDOM_FLAT_STABLE and RANDOM_PROPORTIONAL_STABLE, that despite choosing randomly, will maintain its decision until a new setI is generated.
