### ISSUE TITLE
Idea isCategory() retrurn True if value is another Idea

### ISSUE THREAD

**Issue by brgsil** [CST-Group/cst#57]
When an Idea has another Idea set as its value, the function isCategory() returns True even if none of the Ideas implements the Category functions.
```java
Idea a = new Idea("A");
Idea b = new Idea("B");
a.setValue(b);
System.out.print(a.isCategory());
$ true
```

**Comment by rgudwin** [comment]
This was corrected in CST v. 1.4.2
