### ISSUE TITLE
Idea.setType(int) should redifine values for category and scope fields

### ISSUE THREAD

**Issue by brgsil** [CST-Group/cst#58]
When setting an `Idea` object type using the `setType()` function, it would be expected that the fields `category` and `scope` are set as well to not create a discrepancy between their information.  Issue arise as well if an Idea is defined only by its `type` number, the `category` is always Property and `scope` is 1.

Problem example:
```java
Idea test = new Idea("Name", 0, "Property", 1)
System.out.print(test.getType() + test.getCategory() + test.getScope())
test.setType(3)
System.out.print(test.getType() + test.getCategory() + test.getScope())
```
Generates:
```bash
$ 1 Property 1
$ 3 Property 1 # Inconsistency
```

**Comment by rgudwin** [comment]
This was corrected in version 1.4.2
