### ISSUE TITLE
MemoryGroup type

### ISSUE THREAD

**Issue by EltonCN** [CST-Group/cst#59]
In [Mind.java#78](https://github.com/CST-Group/cst/blob/5429afad7218f98e687cc437e209059973f0bfda/src/main/java/br/unicamp/cst/core/entities/Mind.java#L78C1-L79C1), MemoryGroup type should be `ArrayList<Memory>` instead of the current `ArrayList<Codelet>`?

**Comment by rgudwin** [comment]
This was corrected in CST 1.4.2
